services:
  web-dev:
    build:
      context: web
      dockerfile: Dockerfile
      target: dev
    restart: "unless-stopped"
    volumes:
      - ./web/:/app
      - astro_node_modules:/app/node_modules
    networks:
      - rao-dev

  caddy:
    container_name: caddy
    image: caddy:2-alpine
    restart: unless-stopped
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./caddy/Caddyfile.dev:/etc/caddy/Caddyfile
      - ./caddy/caddy_data:/data
      - ./caddy/caddy_config:/config
    networks:
      - rao-dev
    depends_on:
      - web-dev

networks:
  rao-dev:

volumes:
  astro_node_modules:
