name: config

on:
  push:
    branches:
      - main
    paths:
      - "caddy/Caddyfile"
      - "docker-compose.yml"
      - "deploy.sh"

  workflow_dispatch: 

jobs:
  alert_cd_action:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Alert deploy script
        run: echo Alert deploy script